### ISSUE TITLE
[BUG] - libtesseract.so.5 and liblept.so.5 not found

### ISSUE THREAD

**Issue by alanwilter** [jitesoft/docker-tesseract-ocr#4] opened 2022-09-14 09:17 UTC
I'm on a Mac Silicon with Docker (Engine: 20.10.17)

Dockerfile:

```dockerfile
FROM jitesoft/tesseract-ocr:latest
RUN train-lang eng --best
```

Then:

```bash
docker buildx build --platform linux/arm64 -t audrey:latest .
docker run --rm -i -t --entrypoint=/bin/bash audrey:latest

tesseract@b290576c9d33:/$ type tesseract 
tesseract is hashed (/usr/local/bin/tesseract)
tesseract@b290576c9d33:/$ ldd /usr/local/bin/tesseract 
        linux-vdso.so.1 (0x0000ffff904f0000)
        libtesseract.so.5 => not found
        liblept.so.5 => not found
        libstdc++.so.6 => /lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000ffff90260000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000ffff901c0000)
        libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000ffff90190000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffff8ffe0000)
        /lib/ld-linux-aarch64.so.1 (0x0000ffff904b7000)
```

This won't work.
**`libtesseract.so.5 => not found`**
**`liblept.so.5 => not found`**

I've tried with `linux/arm64` (Intel) and got the same issue.

**Comment by Johannestegner** [comment] 2022-09-16 08:44
Hi!

Thank you for the report, I can reproduce the issue, so will take a look at it and update the images as soon as I have found a fix.

**Comment by Johannestegner** [comment] 2022-09-16 08:57
Update: It seems like the ubuntu 22.04 image build has the wrong version of a few libs. I'm trying to fix the problem, but if you are in a hurry, I'd recommend using the 20.04 tag for now: `jitesoft/tesseract-ocr:22.04` (uses v5 of tesseract and seems to work as intended as of now!).

**Comment by Johannestegner** [comment] 2022-09-16 09:09
The issue was an extra `=` in version check for ubuntu version in the dockerfile:

```
+ && if [ "${UBUNTU_VERSION}" = "22.04" ]; then apt-get -y install libgomp1 libgif7 libwebpmux3 libwebp7 libopenjp2-7 libpng16-16 libjpeg9 libtiff5 zlib1g wget; fi \
  
- && if [ "${UBUNTU_VERSION}" == "22.04" ]; then apt-get -y install libgomp1 libgif7 libwebpmux3 libwebp7 libopenjp2-7 libpng16-16 libjpeg9 libtiff5 zlib1g wget; fi \
```

Re-building all images now, closing this issue :)

Thanks again!

**Closed as completed by Johannestegner** 2022-09-16 09:09 UTC
Labels: bug
